kind: Deployment
apiVersion: apps/v1
metadata:
  name: kibana
  namespace: logging
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: 'docker.elastic.co/kibana/kibana-oss:7.10.2'
          ports:
            - containerPort: 5601
          resources: {}
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200
            - name: XPACK_SECURITY_ENABLED
              value: "true"
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: kibana-config
                  key: elasticsearch_username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: kibana-config
                  key: elasticsearch_password
            - name: SERVER_NAME
              value: kibana
          envFrom:
            - configMapRef:
                name: kibana-config

---
kind: Service
apiVersion: v1
metadata:
  name: kibana
  namespace: logging
spec:
  selector:
    app: kibana
  type: LoadBalancer
  ports:
    - name: http-5601
      protocol: TCP
      port: 5601
      targetPort: 5601 
      nodePort: 30002